// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ECContext))]
    [Migration("20250810084510_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ergonomic wireless mouse with USB receiver",
                            ImageUrl = "https://example.com/products/mouse.jpg",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 149.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Description = "RGB mechanical keyboard with blue switches",
                            ImageUrl = "https://example.com/products/keyboard.jpg",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 349.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Description = "24-inch full HD monitor with HDMI input",
                            ImageUrl = "https://example.com/products/monitor.jpg",
                            IsActive = true,
                            Name = "HD Monitor",
                            Price = 899.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Description = "6-in-1 USB-C hub with HDMI and SD card reader",
                            ImageUrl = "https://example.com/products/hub.jpg",
                            IsActive = true,
                            Name = "USB-C Hub",
                            Price = 79.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "Over-ear gaming headset with noise cancellation",
                            ImageUrl = "https://example.com/products/headset.jpg",
                            IsActive = true,
                            Name = "Gaming Headset",
                            Price = 249.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Description = "High-speed 1TB portable SSD with USB 3.2",
                            ImageUrl = "https://example.com/products/ssd.jpg",
                            IsActive = true,
                            Name = "Portable SSD 1TB",
                            Price = 1199.99m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            Description = "Full HD webcam with built-in microphone",
                            ImageUrl = "https://example.com/products/webcam.jpg",
                            IsActive = true,
                            Name = "Webcam 1080p",
                            Price = 199.95m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 8,
                            Description = "Portable Bluetooth speaker with 12-hour battery life",
                            ImageUrl = "https://example.com/products/speaker.jpg",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 329.99m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 9,
                            Description = "Fitness tracking smartwatch with heart rate monitor",
                            ImageUrl = "https://example.com/products/smartwatch.jpg",
                            IsActive = true,
                            Name = "Smartwatch",
                            Price = 499.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            Description = "Adjustable aluminum laptop stand for desk use",
                            ImageUrl = "https://example.com/products/laptopstand.jpg",
                            IsActive = true,
                            Name = "Laptop Stand",
                            Price = 89.00m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 11,
                            Description = "Fast wireless charger for all Qi-enabled devices",
                            ImageUrl = "https://example.com/products/charger.jpg",
                            IsActive = true,
                            Name = "Wireless Charger",
                            Price = 179.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 12,
                            Description = "In-ear noise-cancelling Bluetooth earbuds",
                            ImageUrl = "https://example.com/products/earbuds.jpg",
                            IsActive = true,
                            Name = "Noise-Cancelling Earbuds",
                            Price = 699.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 13,
                            Description = "Professional graphic tablet with pressure sensitivity",
                            ImageUrl = "https://example.com/products/tablet.jpg",
                            IsActive = true,
                            Name = "Graphic Tablet",
                            Price = 1299.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            Description = "Smart LED lamp with voice control and color settings",
                            ImageUrl = "https://example.com/products/lamp.jpg",
                            IsActive = true,
                            Name = "Smart Lamp",
                            Price = 259.50m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 15,
                            Description = "2TB external hard drive with USB 3.0",
                            ImageUrl = "https://example.com/products/hdd.jpg",
                            IsActive = true,
                            Name = "External Hard Drive 2TB",
                            Price = 649.99m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 16,
                            Description = "Fitness tracker with sleep and step monitoring",
                            ImageUrl = "https://example.com/products/fitnesstracker.jpg",
                            IsActive = true,
                            Name = "Fitness Tracker",
                            Price = 299.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 17,
                            Description = "Waterproof 4K action camera with accessories",
                            ImageUrl = "https://example.com/products/camera.jpg",
                            IsActive = true,
                            Name = "4K Action Camera",
                            Price = 799.99m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 18,
                            Description = "USB condenser microphone for streaming and recording",
                            ImageUrl = "https://example.com/products/mic.jpg",
                            IsActive = true,
                            Name = "Desktop Microphone",
                            Price = 329.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 19,
                            Description = "3-port HDMI switch with remote control",
                            ImageUrl = "https://example.com/products/hdmiswitch.jpg",
                            IsActive = true,
                            Name = "HDMI Switch",
                            Price = 99.99m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 20,
                            Description = "Dual-band gigabit wireless router with wide coverage",
                            ImageUrl = "https://example.com/products/router.jpg",
                            IsActive = true,
                            Name = "Wireless Router",
                            Price = 599.00m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 21,
                            Description = "Color-changing LED strip with remote and app control",
                            ImageUrl = "https://example.com/products/ledstrip.jpg",
                            IsActive = true,
                            Name = "LED Strip Light",
                            Price = 119.99m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 22,
                            Description = "High-back ergonomic office chair with lumbar support",
                            ImageUrl = "https://example.com/products/chair.jpg",
                            IsActive = true,
                            Name = "Ergonomic Office Chair",
                            Price = 1599.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 23,
                            Description = "Next-gen virtual reality headset with motion tracking",
                            ImageUrl = "https://example.com/products/vr.jpg",
                            IsActive = true,
                            Name = "VR Headset",
                            Price = 1999.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 24,
                            Description = "Compact projector with HDMI and USB support",
                            ImageUrl = "https://example.com/products/projector.jpg",
                            IsActive = true,
                            Name = "Mini Projector",
                            Price = 499.99m,
                            Stock = 26
                        },
                        new
                        {
                            Id = 25,
                            Description = "4K media streaming stick with voice remote",
                            ImageUrl = "https://example.com/products/stream.jpg",
                            IsActive = true,
                            Name = "Streaming Stick",
                            Price = 299.00m,
                            Stock = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
